# TODO: (vatshank) add TB2 related fields. (dataset.name)
max_llm_iterations: 500
env:
  env_type: docker  # "docker" or "local"
  retry:
    retry_on_no_change:
        max_attempts: 1
  timeout: 200
  docker:
    base_image: "swebench/sweb.eval.x86_64.django_1776_django-15987"
    workdir: "/testbed"
    hold_command: "bash" # TODO: can be done with docker api instead?
    command_prefix: "source /opt/miniconda3/etc/profile.d/conda.sh && conda activate testbed"
    root_setup_commands: []
    setup_commands: []
    tool_install_commands: []
    internet_access: False
  local:
    workdir: "/home/gauravaz/workplace/CSM_swe/src/CodeStateMachinesSWEBench/src/examples/swebench/scripts/csm_output"

aws:
  region: "us-east-1"

dataset:
  name: sbv # tb2 or sbv or sbpro
  identifier: django__django-15987
  issue_description:

agent:
  agent_id: SimpleResolverAgent
  model: anthropic.claude-opus-4-7
  conversation_manager:
    win_len: 800
  prompt_tag: Anthropic_v2
  invoker: bedrock_mantle
  prompt_caching: False
  prompt_caching_params:
    strategy: custom
    cache_period: 1
  invoker_params:
    max_tokens: 64_000
    thinking:
      type: adaptive
    output_config:
      effort: max

  tools:
    bash:
    str_replace_editor:
      restrict_workspace_create: False
      allow_overwrite: true


hydra:
  run:
    dir: ./outputs/swebench/${now:%Y-%m-%d}/${now:%H-%M-%S}

  job_logging:
    captures:
        stdout: true
        stderr: true