max_llm_iterations: 500
env:
  env_type: docker  # "docker" or "local"
  retry:
    retry_second_chance:
        max_attempts: 1
  timeout: 120
  docker:
    base_image: "swebench/sweb.eval.x86_64.django_1776_django-15987"
    workdir: "/app"
    hold_command: "bash"
    command_prefix: ""
    root_setup_commands: ["apt-get update && apt-get install ripgrep"]
    setup_commands: []
    tool_install_commands: []
    internet_access: true
  local:
    workdir: "/home/gauravaz/workplace/CSM_swe/src/CodeStateMachinesSWEBench/src/examples/swebench/scripts/csm_output"

aws:
  region: "us-west-2"

dataset:
  name: tb2 # tb2 or sbv or sbpro
  identifier: password-recovery
  issue_description:

agent:
  agent_id: SimpleResolverAgent
  model: openai/gpt-5.3-codex
  prompt_tag: tb2_gpt
  invoker: openai
  invoker_params:
    use_previous_id: true # if true, will enable previous_response_id in agentic tool calls
    reasoning:
      effort: xhigh

  tools:
    openai.batch_shell:

hydra:
  run:
    dir: ./outputs/swebench/${now:%Y-%m-%d}/${now:%H-%M-%S}

  job_logging:
    captures:
        stdout: true
        stderr: true
